import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext.js';
import {
  CreditCard,
  Plus,
  Search,
  MessageSquare,
  Printer,
  CheckCircle2,
  AlertCircle,
  RefreshCw,
  Receipt,
  Download,
  IndianRupee,
  Sparkles,
  ArrowUpRight
} from 'lucide-react';
import { FeePayment, Student } from '../types/index.js';
import { apiFetch } from '../lib/api.js';

export const FeesModule: React.FC = () => {
  const { token, currentSchool, showToast } = useAuth();

  const [fees, setFees] = useState<FeePayment[]>([]);
  const [students, setStudents] = useState<Student[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(true);
  const [showPayModal, setShowPayModal] = useState<boolean>(false);
  const [search, setSearch] = useState<string>('');

  const [formData, setFormData] = useState({
    student_id: '',
    amount: 5000,
    month: 'August 2026',
    payment_mode: 'UPI' as 'CASH' | 'UPI' | 'NET_BANKING' | 'CHEQUE',
    remarks: 'Monthly Tuition Fee'
  });

  const fetchFeesAndStudents = async () => {
    setIsLoading(true);
    try {
      const [feesRes, stuRes] = await Promise.all([
        apiFetch('/api/school/fees', { headers: { Authorization: `Bearer ${token}` } }),
        apiFetch('/api/school/students', { headers: { Authorization: `Bearer ${token}` } })
      ]);
      const feesData = await feesRes.json();
      const stuData = await stuRes.json();

      if (feesData.success) setFees(feesData.data || []);
      if (stuData.success) setStudents(stuData.data || []);
    } catch (e) {
      showToast('Error loading fee records.', 'error');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchFeesAndStudents();
  }, []);

  const handleRecordPayment = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.student_id) {
      showToast('Please select a student.', 'error');
      return;
    }

    try {
      const res = await apiFetch('/api/school/fees/collect', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`
        },
        body: JSON.stringify(formData)
      });
      const data = await res.json();
      if (data.success) {
        showToast('✓ Fee receipt logged & verified!', 'success');
        setShowPayModal(false);
        fetchFeesAndStudents();
      } else {
        showToast(data.message || 'Failed to record fee payment.', 'error');
      }
    } catch (e) {
      showToast('Network error saving fee.', 'error');
    }
  };

  const handleWhatsAppReceipt = (fee: FeePayment) => {
    const student = students.find(s => s.student_id === fee.student_id);
    const phone = student?.parent_whatsapp || student?.parent_mobile || currentSchool?.contact_phone || '919876543210';
    const cleanPhone = phone.replace(/[^0-9]/g, '');

    const receiptNo = fee.receipt_number || fee.fee_id || 'REC-2026-001';
    const amount = fee.paid_amount || fee.amount || 0;
    const studentName = fee.student_name || student?.student_name || 'Student';
    const month = fee.month || fee.fee_type || 'Tuition';
    const schoolName = currentSchool?.school_name || 'School';

    const msg = `🧾 *OFFICIAL FEE PAYMENT RECEIPT*\n*${schoolName}*\n\n` +
      `👤 *Student:* ${studentName}\n` +
      `🆔 *Student ID:* ${fee.student_id || '-'}\n` +
      `📑 *Receipt No:* ${receiptNo}\n` +
      `📅 *Month/Fee:* ${month}\n` +
      `💰 *Amount Paid:* ₹${amount.toLocaleString()}\n` +
      `💳 *Payment Mode:* ${fee.payment_mode || 'UPI'}\n` +
      `📅 *Date:* ${fee.payment_date || new Date().toISOString().split('T')[0]}\n\n` +
      `Thank you for the prompt fee payment!\n` +
      `_Automated acknowledgment generated by SchoolOS._`;

    const encoded = encodeURI(msg);
    const url = `https://wa.me/${cleanPhone.startsWith('91') ? cleanPhone : '91' + cleanPhone}?text=${encoded}`;
    window.open(url, '_blank');
    showToast('WhatsApp fee receipt opened. Click Send.', 'info');
  };

  const filteredFees = fees.filter(f => {
    const q = (search || '').toLowerCase();
    const rNo = (f.receipt_number || f.fee_id || '').toLowerCase();
    const sName = (f.student_name || '').toLowerCase();
    const sId = (f.student_id || '').toLowerCase();
    const m = (f.month || f.fee_type || '').toLowerCase();
    return !search || rNo.includes(q) || sName.includes(q) || sId.includes(q) || m.includes(q);
  });

  const totalCollected = fees.reduce((acc, curr) => acc + (curr.paid_amount || curr.amount || 0), 0);

  return (
    <div id="schoolos_fees_module" className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-cyan-600 via-teal-600 to-blue-600 text-white flex items-center justify-center shadow-lg shadow-cyan-600/25 border border-white/20">
              <CreditCard className="w-5 h-5" />
            </div>
            <h2 className="text-xl sm:text-2xl font-black tracking-tight text-slate-900">Fees & Fee Receipts</h2>
          </div>
          <p className="text-xs text-slate-700 mt-1">
            Collect student fees, issue official receipts, and share instant WhatsApp payment acknowledgments.
          </p>
        </div>

        <button
          id="btn_open_collect_fee_modal"
          onClick={() => setShowPayModal(true)}
          className="flex items-center gap-2 px-5 py-2.5 rounded-2xl bg-gradient-to-r from-cyan-600 via-teal-600 to-blue-600 hover:from-cyan-700 hover:to-blue-700 text-white font-black text-xs shadow-lg shadow-cyan-600/25 transition active:scale-95 w-fit"
        >
          <Plus className="w-4 h-4" />
          <span>+ Collect Fees</span>
        </button>
      </div>

      {/* 3D Stats Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <div className="p-5 rounded-3xl bg-white border border-slate-200/90 shadow-sm hover:shadow-md transition space-y-1 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-bl from-emerald-500/10 to-transparent rounded-bl-3xl"></div>
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Total Fees Collected</p>
          <p className="text-2xl sm:text-3xl font-black text-emerald-600 flex items-center">
            ₹{totalCollected.toLocaleString()}
          </p>
          <span className="text-[11px] font-bold text-emerald-700 flex items-center gap-1">
            <CheckCircle2 className="w-3.5 h-3.5" />
            Real-time reconciliation
          </span>
        </div>

        <div className="p-5 rounded-3xl bg-white border border-slate-200/90 shadow-sm hover:shadow-md transition space-y-1 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-bl from-cyan-500/10 to-transparent rounded-bl-3xl"></div>
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Receipts Issued</p>
          <p className="text-2xl sm:text-3xl font-black text-cyan-600">{fees.length}</p>
          <span className="text-[11px] font-medium text-slate-500">Official voucher records</span>
        </div>

        <div className="p-5 rounded-3xl bg-white border border-slate-200/90 shadow-sm hover:shadow-md transition space-y-1 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-24 h-24 bg-gradient-to-bl from-indigo-500/10 to-transparent rounded-bl-3xl"></div>
          <p className="text-xs font-bold text-slate-500 uppercase tracking-wider">Academic Session</p>
          <p className="text-2xl sm:text-3xl font-black text-indigo-700">{currentSchool?.academic_session || '2026-2027'}</p>
          <span className="text-[11px] font-bold text-indigo-600">Standard Schedule</span>
        </div>
      </div>

      {/* Search & Actions Toolbar */}
      <div className="p-4 rounded-3xl bg-white border border-slate-200 shadow-sm flex items-center justify-between gap-4">
        <div className="relative max-w-md w-full">
          <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search by receipt number, student name, or ID..."
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full pl-10 pr-4 py-2.5 bg-slate-50 rounded-2xl border border-slate-300 text-xs text-slate-800 focus:ring-2 focus:ring-cyan-600 outline-none"
          />
        </div>

        <button
          onClick={fetchFeesAndStudents}
          className="p-2.5 rounded-2xl border border-slate-300 text-slate-600 hover:bg-slate-50 transition active:scale-95 shadow-2xs"
          title="Refresh Fee List"
        >
          <RefreshCw className={`w-4 h-4 ${isLoading ? 'animate-spin text-cyan-600' : ''}`} />
        </button>
      </div>

      {/* Receipts Table */}
      {isLoading ? (
        <div className="p-16 text-center bg-white rounded-3xl border border-slate-200">
          <RefreshCw className="w-8 h-8 text-cyan-600 animate-spin mx-auto mb-2" />
          <p className="text-xs font-bold text-slate-700">Loading Fee Ledger...</p>
        </div>
      ) : filteredFees.length === 0 ? (
        <div className="p-16 text-center bg-white rounded-3xl border border-slate-200">
          <Receipt className="w-12 h-12 text-slate-300 mx-auto mb-3" />
          <h3 className="text-sm font-bold text-slate-800">No fee transactions found</h3>
          <button
            onClick={() => setShowPayModal(true)}
            className="mt-4 px-5 py-2.5 bg-cyan-600 hover:bg-cyan-700 text-white text-xs font-bold rounded-2xl shadow-md transition active:scale-95"
          >
            + Record First Payment
          </button>
        </div>
      ) : (
        <div className="bg-white rounded-3xl border border-slate-200 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-900 text-white text-[11px] font-black uppercase tracking-wider">
                  <th className="py-3.5 px-4">Receipt No.</th>
                  <th className="py-3.5 px-4">Student</th>
                  <th className="py-3.5 px-3">Month / Type</th>
                  <th className="py-3.5 px-3">Amount</th>
                  <th className="py-3.5 px-3">Payment Mode</th>
                  <th className="py-3.5 px-3">Date</th>
                  <th className="py-3.5 px-4 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-xs">
                {filteredFees.map(fee => (
                  <tr key={fee.fee_id} className="hover:bg-slate-50/70 transition">
                    <td className="py-3.5 px-4 font-mono font-black text-cyan-700">
                      {fee.receipt_number || fee.fee_id}
                    </td>

                    <td className="py-3.5 px-4 font-bold text-slate-900">
                      <div>
                        <p>{fee.student_name}</p>
                        <span className="text-[10px] text-slate-500 font-mono font-normal">
                          {fee.student_id}
                        </span>
                      </div>
                    </td>

                    <td className="py-3.5 px-3 font-semibold text-slate-700">
                      {fee.month || fee.fee_type || 'Tuition'}
                    </td>

                    <td className="py-3.5 px-3 font-black text-slate-900 text-sm">
                      ₹{(fee.paid_amount || fee.amount || 0).toLocaleString()}
                    </td>

                    <td className="py-3.5 px-3">
                      <span className="px-2.5 py-1 rounded-xl bg-slate-100 font-black text-slate-800 text-[10px] uppercase">
                        {fee.payment_mode || 'UPI'}
                      </span>
                    </td>

                    <td className="py-3.5 px-3 text-slate-600 font-medium">
                      {fee.payment_date || fee.created_at?.split('T')[0] || '-'}
                    </td>

                    <td className="py-3.5 px-4 text-right">
                      <button
                        onClick={() => handleWhatsAppReceipt(fee)}
                        className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-[11px] shadow-sm shadow-emerald-600/20 transition active:scale-95"
                        title="Share WhatsApp Receipt with Parent"
                      >
                        <MessageSquare className="w-3.5 h-3.5" />
                        <span>WhatsApp Receipt</span>
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {/* RECORD PAYMENT MODAL */}
      {showPayModal && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 z-50 animate-in zoom-in-95 duration-150">
          <div className="bg-white rounded-3xl border border-slate-200 p-6 max-w-md w-full shadow-2xl space-y-4">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <div className="flex items-center gap-2">
                <div className="w-8 h-8 rounded-xl bg-cyan-100 text-cyan-700 flex items-center justify-center">
                  <CreditCard className="w-4 h-4" />
                </div>
                <h3 className="text-base font-bold text-slate-900">Collect School Fees</h3>
              </div>
              <button
                onClick={() => setShowPayModal(false)}
                className="p-1 text-slate-400 hover:text-slate-700 rounded-lg"
              >
                ✕
              </button>
            </div>

            <form onSubmit={handleRecordPayment} className="space-y-3.5">
              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  Select Student *
                </label>
                <select
                  required
                  value={formData.student_id}
                  onChange={e => setFormData({ ...formData, student_id: e.target.value })}
                  className="w-full px-3.5 py-2.5 rounded-2xl border border-slate-300 bg-white text-xs font-bold text-slate-900 focus:ring-2 focus:ring-cyan-600 outline-none"
                >
                  <option value="">-- Choose student --</option>
                  {students.map(s => (
                    <option key={s.student_id} value={s.student_id}>
                      {s.student_name} (Class {s.class}-{s.section} • Roll {s.roll_number})
                    </option>
                  ))}
                </select>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">
                  Amount in INR (₹) *
                </label>
                <input
                  type="number"
                  required
                  min="1"
                  value={formData.amount}
                  onChange={e => setFormData({ ...formData, amount: Number(e.target.value) })}
                  className="w-full px-3.5 py-2.5 rounded-2xl border border-slate-300 bg-white text-sm font-bold text-slate-900 focus:ring-2 focus:ring-cyan-600 outline-none"
                />
              </div>

              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Fee Month</label>
                  <input
                    type="text"
                    value={formData.month}
                    onChange={e => setFormData({ ...formData, month: e.target.value })}
                    className="w-full px-3.5 py-2 rounded-2xl border border-slate-300 bg-white text-xs font-semibold outline-none"
                  />
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 mb-1">Payment Mode</label>
                  <select
                    value={formData.payment_mode}
                    onChange={e => setFormData({ ...formData, payment_mode: e.target.value as any })}
                    className="w-full px-3.5 py-2 rounded-2xl border border-slate-300 bg-white text-xs font-bold outline-none"
                  >
                    <option value="UPI">UPI / QR</option>
                    <option value="CASH">Cash</option>
                    <option value="NET_BANKING">Net Banking</option>
                    <option value="CHEQUE">Cheque</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 mb-1">Remarks</label>
                <input
                  type="text"
                  value={formData.remarks}
                  onChange={e => setFormData({ ...formData, remarks: e.target.value })}
                  className="w-full px-3.5 py-2 rounded-2xl border border-slate-300 bg-white text-xs outline-none"
                />
              </div>

              <div className="flex items-center justify-end gap-2 pt-3 border-t border-slate-100">
                <button
                  type="button"
                  onClick={() => setShowPayModal(false)}
                  className="px-4 py-2.5 text-xs font-bold text-slate-700 hover:bg-slate-100 rounded-2xl"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-5 py-2.5 rounded-2xl bg-cyan-600 hover:bg-cyan-700 text-white font-bold text-xs shadow-md shadow-cyan-600/20 transition active:scale-95"
                >
                  Record Payment & Issue Receipt
                </button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};
